# Generated by Django 3.2.7 on 2021-10-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=55)),
                ('tg_username', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=55)),
                ('answers', models.CharField(max_length=55)),
            ],
        ),
    ]
